// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleByCode = `-- name: AssignRoleByCode :one
INSERT INTO user_roles (
    id,
    user_id,
    role_id,
    assigned_by,
    assigned_at,
    expires_at,
    created_at
)
SELECT
    $1,
    $2,
    r.id,
    $4,
    $5,
    NULL,
    $6
FROM auth_roles r
WHERE r.code = $3
    AND r.enabled = TRUE
ON CONFLICT (user_id, role_id) DO UPDATE
SET assigned_by = EXCLUDED.assigned_by
RETURNING
    id,
    user_id,
    role_id,
    assigned_by,
    assigned_at,
    expires_at,
    created_at
`

type AssignRoleByCodeParams struct {
	ID         string             `db:"id" json:"id"`
	UserID     string             `db:"user_id" json:"user_id"`
	Code       string             `db:"code" json:"code"`
	AssignedBy pgtype.Text        `db:"assigned_by" json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) AssignRoleByCode(ctx context.Context, arg AssignRoleByCodeParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, assignRoleByCode,
		arg.ID,
		arg.UserID,
		arg.Code,
		arg.AssignedBy,
		arg.AssignedAt,
		arg.CreatedAt,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countManagedUsers = `-- name: CountManagedUsers :one
SELECT count(*)::bigint
FROM auth_users u
WHERE u.deleted_at IS NULL
    AND u.id <> $1
    AND ($2::text = '' OR u.username ILIKE '%' || $2::text || '%')
    AND ($3::text = '' OR u.status = $3::text)
    AND NOT EXISTS (
        SELECT 1
        FROM user_roles ur
        INNER JOIN auth_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
            AND r.code = ANY($4::text[])
            AND NOT (r.code = ANY($5::text[]))
            AND r.enabled = TRUE
            AND (ur.expires_at IS NULL OR ur.expires_at > now())
    )
    AND EXISTS (
        SELECT 1
        FROM user_roles ur
        INNER JOIN auth_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
            AND r.code = ANY($5::text[])
            AND ($6::text = '' OR r.code = $6::text)
            AND r.enabled = TRUE
            AND (ur.expires_at IS NULL OR ur.expires_at > now())
    )
`

type CountManagedUsersParams struct {
	ActorUserID     string   `db:"actor_user_id" json:"actor_user_id"`
	Username        string   `db:"username" json:"username"`
	Status          string   `db:"status" json:"status"`
	ManagedRoles    []string `db:"managed_roles" json:"managed_roles"`
	ManageableRoles []string `db:"manageable_roles" json:"manageable_roles"`
	Role            string   `db:"role" json:"role"`
}

func (q *Queries) CountManagedUsers(ctx context.Context, arg CountManagedUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManagedUsers,
		arg.ActorUserID,
		arg.Username,
		arg.Status,
		arg.ManagedRoles,
		arg.ManageableRoles,
		arg.Role,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO auth_credentials (
    id,
    user_id,
    credential_type,
    password_hash,
    password_hash_alg,
    password_hash_params_version,
    password_hash_params_json,
    must_change_password,
    password_changed_at,
    password_expires_at,
    failed_attempt_count,
    last_failed_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9, $10, 0, NULL, $11, $12)
RETURNING
    id,
    user_id,
    credential_type,
    password_hash,
    password_hash_alg,
    password_hash_params_version,
    password_hash_params_json,
    must_change_password,
    password_changed_at,
    password_expires_at,
    failed_attempt_count,
    last_failed_at,
    created_at,
    updated_at
`

type CreateCredentialParams struct {
	ID                        string             `db:"id" json:"id"`
	UserID                    string             `db:"user_id" json:"user_id"`
	CredentialType            string             `db:"credential_type" json:"credential_type"`
	PasswordHash              string             `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string             `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string             `db:"password_hash_params_version" json:"password_hash_params_version"`
	Column7                   []byte             `db:"column_7" json:"column_7"`
	MustChangePassword        bool               `db:"must_change_password" json:"must_change_password"`
	PasswordChangedAt         pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	PasswordExpiresAt         pgtype.Timestamptz `db:"password_expires_at" json:"password_expires_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CreateCredentialRow struct {
	ID                        string             `db:"id" json:"id"`
	UserID                    string             `db:"user_id" json:"user_id"`
	CredentialType            string             `db:"credential_type" json:"credential_type"`
	PasswordHash              string             `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string             `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string             `db:"password_hash_params_version" json:"password_hash_params_version"`
	PasswordHashParamsJson    []byte             `db:"password_hash_params_json" json:"password_hash_params_json"`
	MustChangePassword        bool               `db:"must_change_password" json:"must_change_password"`
	PasswordChangedAt         pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	PasswordExpiresAt         pgtype.Timestamptz `db:"password_expires_at" json:"password_expires_at"`
	FailedAttemptCount        int32              `db:"failed_attempt_count" json:"failed_attempt_count"`
	LastFailedAt              pgtype.Timestamptz `db:"last_failed_at" json:"last_failed_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (CreateCredentialRow, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.CredentialType,
		arg.PasswordHash,
		arg.PasswordHashAlg,
		arg.PasswordHashParamsVersion,
		arg.Column7,
		arg.MustChangePassword,
		arg.PasswordChangedAt,
		arg.PasswordExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateCredentialRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialType,
		&i.PasswordHash,
		&i.PasswordHashAlg,
		&i.PasswordHashParamsVersion,
		&i.PasswordHashParamsJson,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.PasswordExpiresAt,
		&i.FailedAttemptCount,
		&i.LastFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSecurityEvent = `-- name: CreateSecurityEvent :exec
INSERT INTO auth_security_events (
    id,
    event_type,
    user_id,
    session_id,
    username_snapshot,
    request_id,
    client_ip,
    user_agent,
    caller_service,
    status,
    reason_code,
    metadata_json,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12::jsonb, $13)
`

type CreateSecurityEventParams struct {
	ID               string             `db:"id" json:"id"`
	EventType        string             `db:"event_type" json:"event_type"`
	UserID           pgtype.Text        `db:"user_id" json:"user_id"`
	SessionID        pgtype.Text        `db:"session_id" json:"session_id"`
	UsernameSnapshot pgtype.Text        `db:"username_snapshot" json:"username_snapshot"`
	RequestID        pgtype.Text        `db:"request_id" json:"request_id"`
	ClientIp         pgtype.Text        `db:"client_ip" json:"client_ip"`
	UserAgent        pgtype.Text        `db:"user_agent" json:"user_agent"`
	CallerService    pgtype.Text        `db:"caller_service" json:"caller_service"`
	Status           string             `db:"status" json:"status"`
	ReasonCode       pgtype.Text        `db:"reason_code" json:"reason_code"`
	Column12         []byte             `db:"column_12" json:"column_12"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateSecurityEvent(ctx context.Context, arg CreateSecurityEventParams) error {
	_, err := q.db.Exec(ctx, createSecurityEvent,
		arg.ID,
		arg.EventType,
		arg.UserID,
		arg.SessionID,
		arg.UsernameSnapshot,
		arg.RequestID,
		arg.ClientIp,
		arg.UserAgent,
		arg.CallerService,
		arg.Status,
		arg.ReasonCode,
		arg.Column12,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
    id,
    user_id,
    access_token_hash,
    access_token_hash_alg,
    access_token_hash_key_version,
    token_type,
    status,
    issued_at,
    expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip,
    user_agent,
    created_request_id,
    revoked_request_id,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, 'Bearer', 'active', $6, $7, NULL, NULL, NULL, $8, $9, $10, NULL, $11, $12)
RETURNING
    id,
    user_id,
    access_token_hash,
    access_token_hash_alg,
    access_token_hash_key_version,
    token_type,
    status,
    issued_at,
    expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip,
    user_agent,
    created_request_id,
    revoked_request_id,
    created_at,
    updated_at
`

type CreateSessionParams struct {
	ID                        string             `db:"id" json:"id"`
	UserID                    string             `db:"user_id" json:"user_id"`
	AccessTokenHash           string             `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenHashAlg        string             `db:"access_token_hash_alg" json:"access_token_hash_alg"`
	AccessTokenHashKeyVersion string             `db:"access_token_hash_key_version" json:"access_token_hash_key_version"`
	IssuedAt                  pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt                 pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ClientIp                  pgtype.Text        `db:"client_ip" json:"client_ip"`
	UserAgent                 pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedRequestID          pgtype.Text        `db:"created_request_id" json:"created_request_id"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AccessTokenHash,
		arg.AccessTokenHashAlg,
		arg.AccessTokenHashKeyVersion,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ClientIp,
		arg.UserAgent,
		arg.CreatedRequestID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionRevocation = `-- name: CreateSessionRevocation :exec
INSERT INTO session_revocations (
    id,
    session_id,
    user_id,
    reason,
    revoked_by,
    request_id,
    revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (session_id) DO NOTHING
`

type CreateSessionRevocationParams struct {
	ID        string             `db:"id" json:"id"`
	SessionID string             `db:"session_id" json:"session_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Reason    string             `db:"reason" json:"reason"`
	RevokedBy pgtype.Text        `db:"revoked_by" json:"revoked_by"`
	RequestID pgtype.Text        `db:"request_id" json:"request_id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) CreateSessionRevocation(ctx context.Context, arg CreateSessionRevocationParams) error {
	_, err := q.db.Exec(ctx, createSessionRevocation,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Reason,
		arg.RevokedBy,
		arg.RequestID,
		arg.RevokedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth_users (
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NULL)
RETURNING
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
`

type CreateUserParams struct {
	ID          string             `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       pgtype.Text        `db:"email" json:"email"`
	Phone       pgtype.Text        `db:"phone" json:"phone"`
	Status      string             `db:"status" json:"status"`
	LockedUntil pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.Status,
		arg.LockedUntil,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteManagedUserRoles = `-- name: DeleteManagedUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
    AND role_id IN (
        SELECT id
        FROM auth_roles
        WHERE code = ANY($2::text[])
    )
`

type DeleteManagedUserRolesParams struct {
	UserID    string   `db:"user_id" json:"user_id"`
	RoleCodes []string `db:"role_codes" json:"role_codes"`
}

func (q *Queries) DeleteManagedUserRoles(ctx context.Context, arg DeleteManagedUserRolesParams) error {
	_, err := q.db.Exec(ctx, deleteManagedUserRoles, arg.UserID, arg.RoleCodes)
	return err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT
    s.id,
    s.user_id,
    s.access_token_hash,
    s.access_token_hash_alg,
    s.access_token_hash_key_version,
    s.token_type,
    s.status,
    s.issued_at,
    s.expires_at,
    s.last_seen_at,
    s.revoked_at,
    s.revoke_reason,
    s.client_ip,
    s.user_agent,
    s.created_request_id,
    s.revoked_request_id,
    s.created_at,
    s.updated_at
FROM auth_sessions s
WHERE s.access_token_hash = $1
    AND s.status = 'active'
    AND s.expires_at > now()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, accessTokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, accessTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT
    id,
    user_id,
    credential_type,
    password_hash,
    password_hash_alg,
    password_hash_params_version,
    password_hash_params_json,
    must_change_password,
    password_changed_at,
    password_expires_at,
    failed_attempt_count,
    last_failed_at,
    created_at,
    updated_at
FROM auth_credentials
WHERE user_id = $1
    AND credential_type = $2
`

type GetCredentialByUserIDParams struct {
	UserID         string `db:"user_id" json:"user_id"`
	CredentialType string `db:"credential_type" json:"credential_type"`
}

type GetCredentialByUserIDRow struct {
	ID                        string             `db:"id" json:"id"`
	UserID                    string             `db:"user_id" json:"user_id"`
	CredentialType            string             `db:"credential_type" json:"credential_type"`
	PasswordHash              string             `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string             `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string             `db:"password_hash_params_version" json:"password_hash_params_version"`
	PasswordHashParamsJson    []byte             `db:"password_hash_params_json" json:"password_hash_params_json"`
	MustChangePassword        bool               `db:"must_change_password" json:"must_change_password"`
	PasswordChangedAt         pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	PasswordExpiresAt         pgtype.Timestamptz `db:"password_expires_at" json:"password_expires_at"`
	FailedAttemptCount        int32              `db:"failed_attempt_count" json:"failed_attempt_count"`
	LastFailedAt              pgtype.Timestamptz `db:"last_failed_at" json:"last_failed_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetCredentialByUserID(ctx context.Context, arg GetCredentialByUserIDParams) (GetCredentialByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, arg.UserID, arg.CredentialType)
	var i GetCredentialByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialType,
		&i.PasswordHash,
		&i.PasswordHashAlg,
		&i.PasswordHashParamsVersion,
		&i.PasswordHashParamsJson,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.PasswordExpiresAt,
		&i.FailedAttemptCount,
		&i.LastFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
    s.id,
    s.user_id,
    s.access_token_hash,
    s.access_token_hash_alg,
    s.access_token_hash_key_version,
    s.token_type,
    s.status,
    s.issued_at,
    s.expires_at,
    s.last_seen_at,
    s.revoked_at,
    s.revoke_reason,
    s.client_ip,
    s.user_agent,
    s.created_request_id,
    s.revoked_request_id,
    s.created_at,
    s.updated_at
FROM auth_sessions s
WHERE s.id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM auth_users
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM auth_users
WHERE username = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listManagedUsers = `-- name: ListManagedUsers :many
SELECT
    u.id,
    u.username,
    u.display_name,
    u.email,
    u.phone,
    u.status,
    u.locked_until,
    u.last_login_at,
    u.created_at,
    u.updated_at,
    u.deleted_at
FROM auth_users u
WHERE u.deleted_at IS NULL
    AND u.id <> $1
    AND ($2::text = '' OR u.username ILIKE '%' || $2::text || '%')
    AND ($3::text = '' OR u.status = $3::text)
    AND NOT EXISTS (
        SELECT 1
        FROM user_roles ur
        INNER JOIN auth_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
            AND r.code = ANY($4::text[])
            AND NOT (r.code = ANY($5::text[]))
            AND r.enabled = TRUE
            AND (ur.expires_at IS NULL OR ur.expires_at > now())
    )
    AND EXISTS (
        SELECT 1
        FROM user_roles ur
        INNER JOIN auth_roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
            AND r.code = ANY($5::text[])
            AND ($6::text = '' OR r.code = $6::text)
            AND r.enabled = TRUE
            AND (ur.expires_at IS NULL OR ur.expires_at > now())
    )
ORDER BY u.created_at DESC, u.id ASC
LIMIT $8
OFFSET $7
`

type ListManagedUsersParams struct {
	ActorUserID     string   `db:"actor_user_id" json:"actor_user_id"`
	Username        string   `db:"username" json:"username"`
	Status          string   `db:"status" json:"status"`
	ManagedRoles    []string `db:"managed_roles" json:"managed_roles"`
	ManageableRoles []string `db:"manageable_roles" json:"manageable_roles"`
	Role            string   `db:"role" json:"role"`
	OffsetCount     int32    `db:"offset_count" json:"offset_count"`
	LimitCount      int32    `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListManagedUsers(ctx context.Context, arg ListManagedUsersParams) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listManagedUsers,
		arg.ActorUserID,
		arg.Username,
		arg.Status,
		arg.ManagedRoles,
		arg.ManageableRoles,
		arg.Role,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionCodesByUserID = `-- name: ListPermissionCodesByUserID :many
SELECT DISTINCT
    p.code
FROM user_roles ur
INNER JOIN auth_roles r
    ON r.id = ur.role_id
INNER JOIN role_permissions rp
    ON rp.role_id = r.id
INNER JOIN auth_permissions p
    ON p.id = rp.permission_id
WHERE ur.user_id = $1
    AND r.enabled = TRUE
    AND p.enabled = TRUE
    AND (ur.expires_at IS NULL OR ur.expires_at > now())
ORDER BY p.code ASC
`

func (q *Queries) ListPermissionCodesByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleCodesByUserID = `-- name: ListRoleCodesByUserID :many
SELECT
    r.code
FROM user_roles ur
INNER JOIN auth_roles r
    ON r.id = ur.role_id
WHERE ur.user_id = $1
    AND r.enabled = TRUE
    AND (ur.expires_at IS NULL OR ur.expires_at > now())
ORDER BY r.code ASC
`

func (q *Queries) ListRoleCodesByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveSessionsForUser = `-- name: RevokeActiveSessionsForUser :many
UPDATE auth_sessions
SET status = 'revoked',
    revoked_at = $2,
    revoke_reason = $3,
    revoked_request_id = $4,
    updated_at = $2
WHERE user_id = $1
    AND status = 'active'
RETURNING
    id,
    user_id,
    access_token_hash,
    access_token_hash_alg,
    access_token_hash_key_version,
    token_type,
    status,
    issued_at,
    expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip,
    user_agent,
    created_request_id,
    revoked_request_id,
    created_at,
    updated_at
`

type RevokeActiveSessionsForUserParams struct {
	UserID           string             `db:"user_id" json:"user_id"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason     pgtype.Text        `db:"revoke_reason" json:"revoke_reason"`
	RevokedRequestID pgtype.Text        `db:"revoked_request_id" json:"revoked_request_id"`
}

func (q *Queries) RevokeActiveSessionsForUser(ctx context.Context, arg RevokeActiveSessionsForUserParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, revokeActiveSessionsForUser,
		arg.UserID,
		arg.RevokedAt,
		arg.RevokeReason,
		arg.RevokedRequestID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthSession
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessTokenHash,
			&i.AccessTokenHashAlg,
			&i.AccessTokenHashKeyVersion,
			&i.TokenType,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.ClientIp,
			&i.UserAgent,
			&i.CreatedRequestID,
			&i.RevokedRequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE auth_sessions
SET status = 'revoked',
    revoked_at = $2,
    revoke_reason = $3,
    revoked_request_id = $4,
    updated_at = $2
WHERE id = $1
    AND status = 'active'
RETURNING
    id,
    user_id,
    access_token_hash,
    access_token_hash_alg,
    access_token_hash_key_version,
    token_type,
    status,
    issued_at,
    expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip,
    user_agent,
    created_request_id,
    revoked_request_id,
    created_at,
    updated_at
`

type RevokeSessionParams struct {
	ID               string             `db:"id" json:"id"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason     pgtype.Text        `db:"revoke_reason" json:"revoke_reason"`
	RevokedRequestID pgtype.Text        `db:"revoked_request_id" json:"revoked_request_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, revokeSession,
		arg.ID,
		arg.RevokedAt,
		arg.RevokeReason,
		arg.RevokedRequestID,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredentialPassword = `-- name: UpdateCredentialPassword :one
UPDATE auth_credentials
SET password_hash = $3,
    password_hash_alg = $4,
    password_hash_params_version = $5,
    password_hash_params_json = $6::jsonb,
    must_change_password = $7,
    password_changed_at = $8,
    failed_attempt_count = 0,
    last_failed_at = NULL,
    updated_at = $8
WHERE user_id = $1
    AND credential_type = $2
RETURNING
    id,
    user_id,
    credential_type,
    password_hash,
    password_hash_alg,
    password_hash_params_version,
    password_hash_params_json,
    must_change_password,
    password_changed_at,
    password_expires_at,
    failed_attempt_count,
    last_failed_at,
    created_at,
    updated_at
`

type UpdateCredentialPasswordParams struct {
	UserID                    string             `db:"user_id" json:"user_id"`
	CredentialType            string             `db:"credential_type" json:"credential_type"`
	PasswordHash              string             `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string             `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string             `db:"password_hash_params_version" json:"password_hash_params_version"`
	Column6                   []byte             `db:"column_6" json:"column_6"`
	MustChangePassword        bool               `db:"must_change_password" json:"must_change_password"`
	PasswordChangedAt         pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
}

type UpdateCredentialPasswordRow struct {
	ID                        string             `db:"id" json:"id"`
	UserID                    string             `db:"user_id" json:"user_id"`
	CredentialType            string             `db:"credential_type" json:"credential_type"`
	PasswordHash              string             `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string             `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string             `db:"password_hash_params_version" json:"password_hash_params_version"`
	PasswordHashParamsJson    []byte             `db:"password_hash_params_json" json:"password_hash_params_json"`
	MustChangePassword        bool               `db:"must_change_password" json:"must_change_password"`
	PasswordChangedAt         pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	PasswordExpiresAt         pgtype.Timestamptz `db:"password_expires_at" json:"password_expires_at"`
	FailedAttemptCount        int32              `db:"failed_attempt_count" json:"failed_attempt_count"`
	LastFailedAt              pgtype.Timestamptz `db:"last_failed_at" json:"last_failed_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateCredentialPassword(ctx context.Context, arg UpdateCredentialPasswordParams) (UpdateCredentialPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateCredentialPassword,
		arg.UserID,
		arg.CredentialType,
		arg.PasswordHash,
		arg.PasswordHashAlg,
		arg.PasswordHashParamsVersion,
		arg.Column6,
		arg.MustChangePassword,
		arg.PasswordChangedAt,
	)
	var i UpdateCredentialPasswordRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialType,
		&i.PasswordHash,
		&i.PasswordHashAlg,
		&i.PasswordHashParamsVersion,
		&i.PasswordHashParamsJson,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.PasswordExpiresAt,
		&i.FailedAttemptCount,
		&i.LastFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLoginAt = `-- name: UpdateUserLastLoginAt :exec
UPDATE auth_users
SET last_login_at = $2,
    updated_at = $2
WHERE id = $1
    AND deleted_at IS NULL
`

type UpdateUserLastLoginAtParams struct {
	ID          string             `db:"id" json:"id"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
}

func (q *Queries) UpdateUserLastLoginAt(ctx context.Context, arg UpdateUserLastLoginAtParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLoginAt, arg.ID, arg.LastLoginAt)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE auth_users
SET display_name = $2,
    email = $3,
    phone = $4,
    updated_at = $5
WHERE id = $1
    AND deleted_at IS NULL
RETURNING
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
`

type UpdateUserProfileParams struct {
	ID          string             `db:"id" json:"id"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       pgtype.Text        `db:"email" json:"email"`
	Phone       pgtype.Text        `db:"phone" json:"phone"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.UpdatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE auth_users
SET status = $2,
    updated_at = $3
WHERE id = $1
    AND deleted_at IS NULL
RETURNING
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
`

type UpdateUserStatusParams struct {
	ID        string             `db:"id" json:"id"`
	Status    string             `db:"status" json:"status"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status, arg.UpdatedAt)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
