// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCredential struct {
	ID                        string             `db:"id" json:"id"`
	UserID                    string             `db:"user_id" json:"user_id"`
	CredentialType            string             `db:"credential_type" json:"credential_type"`
	PasswordHash              string             `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string             `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string             `db:"password_hash_params_version" json:"password_hash_params_version"`
	PasswordHashParamsJson    []byte             `db:"password_hash_params_json" json:"password_hash_params_json"`
	PasswordChangedAt         pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	PasswordExpiresAt         pgtype.Timestamptz `db:"password_expires_at" json:"password_expires_at"`
	FailedAttemptCount        int32              `db:"failed_attempt_count" json:"failed_attempt_count"`
	LastFailedAt              pgtype.Timestamptz `db:"last_failed_at" json:"last_failed_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MustChangePassword        bool               `db:"must_change_password" json:"must_change_password"`
}

type AuthPermission struct {
	ID          string             `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Domain      string             `db:"domain" json:"domain"`
	Action      string             `db:"action" json:"action"`
	Description string             `db:"description" json:"description"`
	Enabled     bool               `db:"enabled" json:"enabled"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuthRole struct {
	ID          string             `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	Enabled     bool               `db:"enabled" json:"enabled"`
	SystemRole  bool               `db:"system_role" json:"system_role"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuthSecurityEvent struct {
	ID               string             `db:"id" json:"id"`
	EventType        string             `db:"event_type" json:"event_type"`
	UserID           pgtype.Text        `db:"user_id" json:"user_id"`
	SessionID        pgtype.Text        `db:"session_id" json:"session_id"`
	UsernameSnapshot pgtype.Text        `db:"username_snapshot" json:"username_snapshot"`
	RequestID        pgtype.Text        `db:"request_id" json:"request_id"`
	ClientIp         pgtype.Text        `db:"client_ip" json:"client_ip"`
	UserAgent        pgtype.Text        `db:"user_agent" json:"user_agent"`
	CallerService    pgtype.Text        `db:"caller_service" json:"caller_service"`
	Status           string             `db:"status" json:"status"`
	ReasonCode       pgtype.Text        `db:"reason_code" json:"reason_code"`
	MetadataJson     []byte             `db:"metadata_json" json:"metadata_json"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthSession struct {
	ID                        string             `db:"id" json:"id"`
	UserID                    string             `db:"user_id" json:"user_id"`
	AccessTokenHash           string             `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenHashAlg        string             `db:"access_token_hash_alg" json:"access_token_hash_alg"`
	AccessTokenHashKeyVersion string             `db:"access_token_hash_key_version" json:"access_token_hash_key_version"`
	TokenType                 string             `db:"token_type" json:"token_type"`
	Status                    string             `db:"status" json:"status"`
	IssuedAt                  pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt                 pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastSeenAt                pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt                 pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason              pgtype.Text        `db:"revoke_reason" json:"revoke_reason"`
	ClientIp                  pgtype.Text        `db:"client_ip" json:"client_ip"`
	UserAgent                 pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedRequestID          pgtype.Text        `db:"created_request_id" json:"created_request_id"`
	RevokedRequestID          pgtype.Text        `db:"revoked_request_id" json:"revoked_request_id"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuthUser struct {
	ID          string             `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Email       pgtype.Text        `db:"email" json:"email"`
	Phone       pgtype.Text        `db:"phone" json:"phone"`
	Status      string             `db:"status" json:"status"`
	LockedUntil pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type RolePermission struct {
	ID           string             `db:"id" json:"id"`
	RoleID       string             `db:"role_id" json:"role_id"`
	PermissionID string             `db:"permission_id" json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SessionRevocation struct {
	ID        string             `db:"id" json:"id"`
	SessionID string             `db:"session_id" json:"session_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Reason    string             `db:"reason" json:"reason"`
	RevokedBy pgtype.Text        `db:"revoked_by" json:"revoked_by"`
	RequestID pgtype.Text        `db:"request_id" json:"request_id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type UserRole struct {
	ID         string             `db:"id" json:"id"`
	UserID     string             `db:"user_id" json:"user_id"`
	RoleID     string             `db:"role_id" json:"role_id"`
	AssignedBy pgtype.Text        `db:"assigned_by" json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
